const mongoose = require("mongoose");
require("dotenv").config();

const Recommendation = require("./models/Recommendation");
const connectDB = require("./config/db");

const problems = [
  {
    title: "Two Sum",
    difficulty: "Easy",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/two-sum/",
  },
  {
    title: "Palindrome Number",
    difficulty: "Easy",
    topic: ["Math"],
    link: "https://leetcode.com/problems/palindrome-number/",
  },
  {
    title: "Roman to Integer",
    difficulty: "Easy",
    topic: ["Hash Table", "Math", "String"],
    link: "https://leetcode.com/problems/roman-to-integer/",
  },
  {
    title: "Longest Common Prefix",
    difficulty: "Easy",
    topic: ["Array", "String", "Trie"],
    link: "https://leetcode.com/problems/longest-common-prefix/",
  },
  {
    title: "Valid Parentheses",
    difficulty: "Easy",
    topic: ["String", "Stack"],
    link: "https://leetcode.com/problems/valid-parentheses/",
  },
  {
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topic: ["Linked List", "Recursion"],
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
  },
  {
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    topic: ["Array", "Two Pointers"],
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
  },
  {
    title: "Remove Element",
    difficulty: "Easy",
    topic: ["Array", "Two Pointers"],
    link: "https://leetcode.com/problems/remove-element/",
  },
  {
    title: "Find the Index of the First Occurrence in a String",
    difficulty: "Easy",
    topic: ["Two Pointers", "String", "String Matching"],
    link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
  },
  {
    title: "Search Insert Position",
    difficulty: "Easy",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/search-insert-position/",
  },
  {
    title: "Length of Last Word",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/length-of-last-word/",
  },
  {
    title: "Plus One",
    difficulty: "Easy",
    topic: ["Array", "Math"],
    link: "https://leetcode.com/problems/plus-one/",
  },
  {
    title: "Add Binary",
    difficulty: "Easy",
    topic: ["Math", "String", "Bit Manipulation", "Simulation"],
    link: "https://leetcode.com/problems/add-binary/",
  },
  {
    title: "Sqrt(x)",
    difficulty: "Easy",
    topic: ["Math", "Binary Search"],
    link: "https://leetcode.com/problems/sqrtx/",
  },
  {
    title: "Climbing Stairs",
    difficulty: "Easy",
    topic: ["Math", "Dynamic Programming", "Memoization"],
    link: "https://leetcode.com/problems/climbing-stairs/",
  },
  {
    title: "Remove Duplicates from Sorted List",
    difficulty: "Easy",
    topic: ["Linked List"],
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/",
  },
  {
    title: "Merge Sorted Array",
    difficulty: "Easy",
    topic: ["Array", "Two Pointers", "Sorting"],
    link: "https://leetcode.com/problems/merge-sorted-array/",
  },
  {
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    topic: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
  },
  {
    title: "Same Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/same-tree/",
  },
  {
    title: "Symmetric Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/symmetric-tree/",
  },
  {
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  },
  {
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: "Easy",
    topic: [
      "Array",
      "Divide and Conquer",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
  },
  {
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/balanced-binary-tree/",
  },
  {
    title: "Minimum Depth of Binary Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/minimum-depth-of-binary-tree/",
  },
  {
    title: "Path Sum",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/path-sum/",
  },
  {
    title: "Pascal's Triangle",
    difficulty: "Easy",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/pascals-triangle/",
  },
  {
    title: "Pascal's Triangle II",
    difficulty: "Easy",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/pascals-triangle-ii/",
  },
  {
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    title: "Valid Palindrome",
    difficulty: "Easy",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/valid-palindrome/",
  },
  {
    title: "Single Number",
    difficulty: "Easy",
    topic: ["Array", "Bit Manipulation"],
    link: "https://leetcode.com/problems/single-number/",
  },
  {
    title: "Linked List Cycle",
    difficulty: "Easy",
    topic: ["Hash Table", "Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/linked-list-cycle/",
  },
  {
    title: "Binary Tree Preorder Traversal",
    difficulty: "Easy",
    topic: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
  },
  {
    title: "Binary Tree Postorder Traversal",
    difficulty: "Easy",
    topic: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
  },
  {
    title: "Intersection of Two Linked Lists",
    difficulty: "Easy",
    topic: ["Hash Table", "Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
  },
  {
    title: "Excel Sheet Column Title",
    difficulty: "Easy",
    topic: ["Math", "String"],
    link: "https://leetcode.com/problems/excel-sheet-column-title/",
  },
  {
    title: "Majority Element",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Counting"],
    link: "https://leetcode.com/problems/majority-element/",
  },
  {
    title: "Excel Sheet Column Number",
    difficulty: "Easy",
    topic: ["Math", "String"],
    link: "https://leetcode.com/problems/excel-sheet-column-number/",
  },
  {
    title: "Combine Two Tables",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/combine-two-tables/",
  },
  {
    title: "Employees Earning More Than Their Managers",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/employees-earning-more-than-their-managers/",
  },
  {
    title: "Duplicate Emails",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/duplicate-emails/",
  },
  {
    title: "Customers Who Never Order",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/customers-who-never-order/",
  },
  {
    title: "Reverse Bits",
    difficulty: "Easy",
    topic: ["Divide and Conquer", "Bit Manipulation"],
    link: "https://leetcode.com/problems/reverse-bits/",
  },
  {
    title: "Number of 1 Bits",
    difficulty: "Easy",
    topic: ["Divide and Conquer", "Bit Manipulation"],
    link: "https://leetcode.com/problems/number-of-1-bits/",
  },
  {
    title: "Valid Phone Numbers",
    difficulty: "Easy",
    topic: ["Shell"],
    link: "https://leetcode.com/problems/valid-phone-numbers/",
  },
  {
    title: "Tenth Line",
    difficulty: "Easy",
    topic: ["Shell"],
    link: "https://leetcode.com/problems/tenth-line/",
  },
  {
    title: "Delete Duplicate Emails",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/delete-duplicate-emails/",
  },
  {
    title: "Rising Temperature",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/rising-temperature/",
  },
  {
    title: "Happy Number",
    difficulty: "Easy",
    topic: ["Hash Table", "Math", "Two Pointers"],
    link: "https://leetcode.com/problems/happy-number/",
  },
  {
    title: "Remove Linked List Elements",
    difficulty: "Easy",
    topic: ["Linked List", "Recursion"],
    link: "https://leetcode.com/problems/remove-linked-list-elements/",
  },
  {
    title: "Isomorphic Strings",
    difficulty: "Easy",
    topic: ["Hash Table", "String"],
    link: "https://leetcode.com/problems/isomorphic-strings/",
  },
  {
    title: "Reverse Linked List",
    difficulty: "Easy",
    topic: ["Linked List", "Recursion"],
    link: "https://leetcode.com/problems/reverse-linked-list/",
  },
  {
    title: "Contains Duplicate",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Sorting"],
    link: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    title: "Contains Duplicate II",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Sliding Window"],
    link: "https://leetcode.com/problems/contains-duplicate-ii/",
  },
  {
    title: "Count Complete Tree Nodes",
    difficulty: "Easy",
    topic: ["Binary Search", "Bit Manipulation", "Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/count-complete-tree-nodes/",
  },
  {
    title: "Implement Stack using Queues",
    difficulty: "Easy",
    topic: ["Stack", "Design", "Queue"],
    link: "https://leetcode.com/problems/implement-stack-using-queues/",
  },
  {
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/invert-binary-tree/",
  },
  {
    title: "Summary Ranges",
    difficulty: "Easy",
    topic: ["Array"],
    link: "https://leetcode.com/problems/summary-ranges/",
  },
  {
    title: "Power of Two",
    difficulty: "Easy",
    topic: ["Math", "Bit Manipulation", "Recursion"],
    link: "https://leetcode.com/problems/power-of-two/",
  },
  {
    title: "Implement Queue using Stacks",
    difficulty: "Easy",
    topic: ["Stack", "Design", "Queue"],
    link: "https://leetcode.com/problems/implement-queue-using-stacks/",
  },
  {
    title: "Palindrome Linked List",
    difficulty: "Easy",
    topic: ["Linked List", "Two Pointers", "Stack", "Recursion"],
    link: "https://leetcode.com/problems/palindrome-linked-list/",
  },
  {
    title: "Valid Anagram",
    difficulty: "Easy",
    topic: ["Hash Table", "String", "Sorting"],
    link: "https://leetcode.com/problems/valid-anagram/",
  },
  {
    title: "Binary Tree Paths",
    difficulty: "Easy",
    topic: [
      "String",
      "Backtracking",
      "Tree",
      "Depth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/binary-tree-paths/",
  },
  {
    title: "Add Digits",
    difficulty: "Easy",
    topic: ["Math", "Simulation", "Number Theory"],
    link: "https://leetcode.com/problems/add-digits/",
  },
  {
    title: "Ugly Number",
    difficulty: "Easy",
    topic: ["Math"],
    link: "https://leetcode.com/problems/ugly-number/",
  },
  {
    title: "Missing Number",
    difficulty: "Easy",
    topic: [
      "Array",
      "Hash Table",
      "Math",
      "Binary Search",
      "Bit Manipulation",
      "Sorting",
    ],
    link: "https://leetcode.com/problems/missing-number/",
  },
  {
    title: "First Bad Version",
    difficulty: "Easy",
    topic: ["Binary Search", "Interactive"],
    link: "https://leetcode.com/problems/first-bad-version/",
  },
  {
    title: "Move Zeroes",
    difficulty: "Easy",
    topic: ["Array", "Two Pointers"],
    link: "https://leetcode.com/problems/move-zeroes/",
  },
  {
    title: "Word Pattern",
    difficulty: "Easy",
    topic: ["Hash Table", "String"],
    link: "https://leetcode.com/problems/word-pattern/",
  },
  {
    title: "Nim Game",
    difficulty: "Easy",
    topic: ["Math", "Brainteaser", "Game Theory"],
    link: "https://leetcode.com/problems/nim-game/",
  },
  {
    title: "Range Sum Query - Immutable",
    difficulty: "Easy",
    topic: ["Array", "Design", "Prefix Sum"],
    link: "https://leetcode.com/problems/range-sum-query-immutable/",
  },
  {
    title: "Power of Three",
    difficulty: "Easy",
    topic: ["Math", "Recursion"],
    link: "https://leetcode.com/problems/power-of-three/",
  },
  {
    title: "Counting Bits",
    difficulty: "Easy",
    topic: ["Dynamic Programming", "Bit Manipulation"],
    link: "https://leetcode.com/problems/counting-bits/",
  },
  {
    title: "Power of Four",
    difficulty: "Easy",
    topic: ["Math", "Bit Manipulation", "Recursion"],
    link: "https://leetcode.com/problems/power-of-four/",
  },
  {
    title: "Reverse String",
    difficulty: "Easy",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/reverse-string/",
  },
  {
    title: "Reverse Vowels of a String",
    difficulty: "Easy",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/reverse-vowels-of-a-string/",
  },
  {
    title: "Intersection of Two Arrays",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Two Pointers", "Binary Search", "Sorting"],
    link: "https://leetcode.com/problems/intersection-of-two-arrays/",
  },
  {
    title: "Intersection of Two Arrays II",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Two Pointers", "Binary Search", "Sorting"],
    link: "https://leetcode.com/problems/intersection-of-two-arrays-ii/",
  },
  {
    title: "Valid Perfect Square",
    difficulty: "Easy",
    topic: ["Math", "Binary Search"],
    link: "https://leetcode.com/problems/valid-perfect-square/",
  },
  {
    title: "Guess Number Higher or Lower",
    difficulty: "Easy",
    topic: ["Binary Search", "Interactive"],
    link: "https://leetcode.com/problems/guess-number-higher-or-lower/",
  },
  {
    title: "Ransom Note",
    difficulty: "Easy",
    topic: ["Hash Table", "String", "Counting"],
    link: "https://leetcode.com/problems/ransom-note/",
  },
  {
    title: "First Unique Character in a String",
    difficulty: "Easy",
    topic: ["Hash Table", "String", "Queue", "Counting"],
    link: "https://leetcode.com/problems/first-unique-character-in-a-string/",
  },
  {
    title: "Find the Difference",
    difficulty: "Easy",
    topic: ["Hash Table", "String", "Bit Manipulation", "Sorting"],
    link: "https://leetcode.com/problems/find-the-difference/",
  },
  {
    title: "Is Subsequence",
    difficulty: "Easy",
    topic: ["Two Pointers", "String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/is-subsequence/",
  },
  {
    title: "Binary Watch",
    difficulty: "Easy",
    topic: ["Backtracking", "Bit Manipulation"],
    link: "https://leetcode.com/problems/binary-watch/",
  },
  {
    title: "Sum of Left Leaves",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/sum-of-left-leaves/",
  },
  {
    title: "Convert a Number to Hexadecimal",
    difficulty: "Easy",
    topic: ["Math", "String", "Bit Manipulation"],
    link: "https://leetcode.com/problems/convert-a-number-to-hexadecimal/",
  },
  {
    title: "Longest Palindrome",
    difficulty: "Easy",
    topic: ["Hash Table", "String", "Greedy"],
    link: "https://leetcode.com/problems/longest-palindrome/",
  },
  {
    title: "Fizz Buzz",
    difficulty: "Easy",
    topic: ["Math", "String", "Simulation"],
    link: "https://leetcode.com/problems/fizz-buzz/",
  },
  {
    title: "Third Maximum Number",
    difficulty: "Easy",
    topic: ["Array", "Sorting"],
    link: "https://leetcode.com/problems/third-maximum-number/",
  },
  {
    title: "Add Strings",
    difficulty: "Easy",
    topic: ["Math", "String", "Simulation"],
    link: "https://leetcode.com/problems/add-strings/",
  },
  {
    title: "Number of Segments in a String",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/number-of-segments-in-a-string/",
  },
  {
    title: "Arranging Coins",
    difficulty: "Easy",
    topic: ["Math", "Binary Search"],
    link: "https://leetcode.com/problems/arranging-coins/",
  },
  {
    title: "Find All Numbers Disappeared in an Array",
    difficulty: "Easy",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
  },
  {
    title: "Assign Cookies",
    difficulty: "Easy",
    topic: ["Array", "Two Pointers", "Greedy", "Sorting"],
    link: "https://leetcode.com/problems/assign-cookies/",
  },
  {
    title: "Repeated Substring Pattern",
    difficulty: "Easy",
    topic: ["String", "String Matching"],
    link: "https://leetcode.com/problems/repeated-substring-pattern/",
  },
  {
    title: "Hamming Distance",
    difficulty: "Easy",
    topic: ["Bit Manipulation"],
    link: "https://leetcode.com/problems/hamming-distance/",
  },
  {
    title: "Island Perimeter",
    difficulty: "Easy",
    topic: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/island-perimeter/",
  },
  {
    title: "Number Complement",
    difficulty: "Easy",
    topic: ["Bit Manipulation"],
    link: "https://leetcode.com/problems/number-complement/",
  },
  {
    title: "License Key Formatting",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/license-key-formatting/",
  },
  {
    title: "Max Consecutive Ones",
    difficulty: "Easy",
    topic: ["Array"],
    link: "https://leetcode.com/problems/max-consecutive-ones/",
  },
  {
    title: "Construct the Rectangle",
    difficulty: "Easy",
    topic: ["Math"],
    link: "https://leetcode.com/problems/construct-the-rectangle/",
  },
  {
    title: "Teemo Attacking",
    difficulty: "Easy",
    topic: ["Array", "Simulation"],
    link: "https://leetcode.com/problems/teemo-attacking/",
  },
  {
    title: "Next Greater Element I",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Stack", "Monotonic Stack"],
    link: "https://leetcode.com/problems/next-greater-element-i/",
  },
  {
    title: "Keyboard Row",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "String"],
    link: "https://leetcode.com/problems/keyboard-row/",
  },
  {
    title: "Find Mode in Binary Search Tree",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/find-mode-in-binary-search-tree/",
  },
  {
    title: "Base 7",
    difficulty: "Easy",
    topic: ["Math", "String"],
    link: "https://leetcode.com/problems/base-7/",
  },
  {
    title: "Relative Ranks",
    difficulty: "Easy",
    topic: ["Array", "Sorting", "Heap (Priority Queue)"],
    link: "https://leetcode.com/problems/relative-ranks/",
  },
  {
    title: "Perfect Number",
    difficulty: "Easy",
    topic: ["Math"],
    link: "https://leetcode.com/problems/perfect-number/",
  },
  {
    title: "Fibonacci Number",
    difficulty: "Easy",
    topic: ["Math", "Dynamic Programming", "Recursion", "Memoization"],
    link: "https://leetcode.com/problems/fibonacci-number/",
  },
  {
    title: "Game Play Analysis I",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/game-play-analysis-i/",
  },
  {
    title: "Detect Capital",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/detect-capital/",
  },
  {
    title: "Longest Uncommon Subsequence I",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/longest-uncommon-subsequence-i/",
  },
  {
    title: "Minimum Absolute Difference in BST",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
  },
  {
    title: "Reverse String II",
    difficulty: "Easy",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/reverse-string-ii/",
  },
  {
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/diameter-of-binary-tree/",
  },
  {
    title: "Student Attendance Record I",
    difficulty: "Easy",
    topic: ["String"],
    link: "https://leetcode.com/problems/student-attendance-record-i/",
  },
  {
    title: "Reverse Words in a String III",
    difficulty: "Easy",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/reverse-words-in-a-string-iii/",
  },
  {
    title: "Maximum Depth of N-ary Tree",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Breadth-First Search"],
    link: "https://leetcode.com/problems/maximum-depth-of-n-ary-tree/",
  },
  {
    title: "Array Partition",
    difficulty: "Easy",
    topic: ["Array", "Greedy", "Sorting", "Counting Sort"],
    link: "https://leetcode.com/problems/array-partition/",
  },
  {
    title: "Binary Tree Tilt",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-tilt/",
  },
  {
    title: "Reshape the Matrix",
    difficulty: "Easy",
    topic: ["Array", "Matrix", "Simulation"],
    link: "https://leetcode.com/problems/reshape-the-matrix/",
  },
  {
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "String Matching",
      "Binary Tree",
      "Hash Function",
    ],
    link: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    title: "Distribute Candies",
    difficulty: "Easy",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/distribute-candies/",
  },
  {
    title: "Employee Bonus",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/employee-bonus/",
  },
  {
    title: "Find Customer Referee",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/find-customer-referee/",
  },
  {
    title: "Customer Placing the Largest Number of Orders",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/customer-placing-the-largest-number-of-orders/",
  },
  {
    title: "N-ary Tree Preorder Traversal",
    difficulty: "Easy",
    topic: ["Stack", "Tree", "Depth-First Search"],
    link: "https://leetcode.com/problems/n-ary-tree-preorder-traversal/",
  },
  {
    title: "N-ary Tree Postorder Traversal",
    difficulty: "Easy",
    topic: ["Stack", "Tree", "Depth-First Search"],
    link: "https://leetcode.com/problems/n-ary-tree-postorder-traversal/",
  },
  {
    title: "Longest Harmonious Subsequence",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Sliding Window", "Sorting", "Counting"],
    link: "https://leetcode.com/problems/longest-harmonious-subsequence/",
  },
  {
    title: "Big Countries",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/big-countries/",
  },
  {
    title: "Classes With at Least 5 Students",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/classes-with-at-least-5-students/",
  },
  {
    title: "Range Addition II",
    difficulty: "Easy",
    topic: ["Array", "Math"],
    link: "https://leetcode.com/problems/range-addition-ii/",
  },
  {
    title: "Minimum Index Sum of Two Lists",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "String"],
    link: "https://leetcode.com/problems/minimum-index-sum-of-two-lists/",
  },
  {
    title: "Can Place Flowers",
    difficulty: "Easy",
    topic: ["Array", "Greedy"],
    link: "https://leetcode.com/problems/can-place-flowers/",
  },
  {
    title: "Sales Person",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/sales-person/",
  },
  {
    title: "Triangle Judgement",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/triangle-judgement/",
  },
  {
    title: "Merge Two Binary Trees",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/merge-two-binary-trees/",
  },
  {
    title: "Biggest Single Number",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/biggest-single-number/",
  },
  {
    title: "Not Boring Movies",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/not-boring-movies/",
  },
  {
    title: "Swap Salary",
    difficulty: "Easy",
    topic: ["Database"],
    link: "https://leetcode.com/problems/swap-salary/",
  },
  {
    title: "Maximum Product of Three Numbers",
    difficulty: "Easy",
    topic: ["Array", "Math", "Sorting"],
    link: "https://leetcode.com/problems/maximum-product-of-three-numbers/",
  },
  {
    title: "Average of Levels in Binary Tree",
    difficulty: "Easy",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/average-of-levels-in-binary-tree/",
  },
  {
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    topic: ["Array", "Sliding Window"],
    link: "https://leetcode.com/problems/maximum-average-subarray-i/",
  },
  {
    title: "Set Mismatch",
    difficulty: "Easy",
    topic: ["Array", "Hash Table", "Bit Manipulation", "Sorting"],
    link: "https://leetcode.com/problems/set-mismatch/",
  },
  {
    title: "Two Sum IV - Input is a BST",
    difficulty: "Easy",
    topic: [
      "Hash Table",
      "Two Pointers",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
  },
  {
    title: "Robot Return to Origin",
    difficulty: "Easy",
    topic: ["String", "Simulation"],
    link: "https://leetcode.com/problems/robot-return-to-origin/",
  },
  {
    title: "Image Smoother",
    difficulty: "Easy",
    topic: ["Array", "Matrix"],
    link: "https://leetcode.com/problems/image-smoother/",
  },
  {
    title: "Second Minimum Node In a Binary Tree",
    difficulty: "Easy",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/second-minimum-node-in-a-binary-tree/",
  },
  {
    title: "Longest Continuous Increasing Subsequence",
    difficulty: "Easy",
    topic: ["Array"],
    link: "https://leetcode.com/problems/longest-continuous-increasing-subsequence/",
  },
  {
    title: "Valid Palindrome II",
    difficulty: "Easy",
    topic: ["Two Pointers", "String", "Greedy"],
    link: "https://leetcode.com/problems/valid-palindrome-ii/",
  },
  {
    title: "Add Two Numbers",
    difficulty: "Medium",
    topic: ["Linked List", "Math", "Recursion"],
    link: "https://leetcode.com/problems/add-two-numbers/",
  },
  {
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    topic: ["Two Pointers", "String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
  },
  {
    title: "Zigzag Conversion",
    difficulty: "Medium",
    topic: ["String"],
    link: "https://leetcode.com/problems/zigzag-conversion/",
  },
  {
    title: "Reverse Integer",
    difficulty: "Medium",
    topic: ["Math"],
    link: "https://leetcode.com/problems/reverse-integer/",
  },
  {
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    topic: ["String"],
    link: "https://leetcode.com/problems/string-to-integer-atoi/",
  },
  {
    title: "Container With Most Water",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Greedy"],
    link: "https://leetcode.com/problems/container-with-most-water/",
  },
  {
    title: "Integer to Roman",
    difficulty: "Medium",
    topic: ["Hash Table", "Math", "String"],
    link: "https://leetcode.com/problems/integer-to-roman/",
  },
  {
    title: "3Sum",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Sorting"],
    link: "https://leetcode.com/problems/3sum/",
  },
  {
    title: "3Sum Closest",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Sorting"],
    link: "https://leetcode.com/problems/3sum-closest/",
  },
  {
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Backtracking"],
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
  },
  {
    title: "4Sum",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Sorting"],
    link: "https://leetcode.com/problems/4sum/",
  },
  {
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    topic: ["Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  },
  {
    title: "Generate Parentheses",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming", "Backtracking"],
    link: "https://leetcode.com/problems/generate-parentheses/",
  },
  {
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    topic: ["Linked List", "Recursion"],
    link: "https://leetcode.com/problems/swap-nodes-in-pairs/",
  },
  {
    title: "Divide Two Integers",
    difficulty: "Medium",
    topic: ["Math", "Bit Manipulation"],
    link: "https://leetcode.com/problems/divide-two-integers/",
  },
  {
    title: "Next Permutation",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers"],
    link: "https://leetcode.com/problems/next-permutation/",
  },
  {
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  },
  {
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
  },
  {
    title: "Valid Sudoku",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Matrix"],
    link: "https://leetcode.com/problems/valid-sudoku/",
  },
  {
    title: "Count and Say",
    difficulty: "Medium",
    topic: ["String"],
    link: "https://leetcode.com/problems/count-and-say/",
  },
  {
    title: "Combination Sum",
    difficulty: "Medium",
    topic: ["Array", "Backtracking"],
    link: "https://leetcode.com/problems/combination-sum/",
  },
  {
    title: "Combination Sum II",
    difficulty: "Medium",
    topic: ["Array", "Backtracking"],
    link: "https://leetcode.com/problems/combination-sum-ii/",
  },
  {
    title: "Multiply Strings",
    difficulty: "Medium",
    topic: ["Math", "String", "Simulation"],
    link: "https://leetcode.com/problems/multiply-strings/",
  },
  {
    title: "Jump Game II",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Greedy"],
    link: "https://leetcode.com/problems/jump-game-ii/",
  },
  {
    title: "Permutations",
    difficulty: "Medium",
    topic: ["Array", "Backtracking"],
    link: "https://leetcode.com/problems/permutations/",
  },
  {
    title: "Permutations II",
    difficulty: "Medium",
    topic: ["Array", "Backtracking", "Sorting"],
    link: "https://leetcode.com/problems/permutations-ii/",
  },
  {
    title: "Rotate Image",
    difficulty: "Medium",
    topic: ["Array", "Math", "Matrix"],
    link: "https://leetcode.com/problems/rotate-image/",
  },
  {
    title: "Group Anagrams",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "String", "Sorting"],
    link: "https://leetcode.com/problems/group-anagrams/",
  },
  {
    title: "Pow(x, n)",
    difficulty: "Medium",
    topic: ["Math", "Recursion"],
    link: "https://leetcode.com/problems/powx-n/",
  },
  {
    title: "Maximum Subarray",
    difficulty: "Medium",
    topic: ["Array", "Divide and Conquer", "Dynamic Programming"],
    link: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    title: "Spiral Matrix",
    difficulty: "Medium",
    topic: ["Array", "Matrix", "Simulation"],
    link: "https://leetcode.com/problems/spiral-matrix/",
  },
  {
    title: "Jump Game",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Greedy"],
    link: "https://leetcode.com/problems/jump-game/",
  },
  {
    title: "Merge Intervals",
    difficulty: "Medium",
    topic: ["Array", "Sorting"],
    link: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    title: "Insert Interval",
    difficulty: "Medium",
    topic: ["Array"],
    link: "https://leetcode.com/problems/insert-interval/",
  },
  {
    title: "Spiral Matrix II",
    difficulty: "Medium",
    topic: ["Array", "Matrix", "Simulation"],
    link: "https://leetcode.com/problems/spiral-matrix-ii/",
  },
  {
    title: "Rotate List",
    difficulty: "Medium",
    topic: ["Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/rotate-list/",
  },
  {
    title: "Unique Paths",
    difficulty: "Medium",
    topic: ["Math", "Dynamic Programming", "Combinatorics"],
    link: "https://leetcode.com/problems/unique-paths/",
  },
  {
    title: "Unique Paths II",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Matrix"],
    link: "https://leetcode.com/problems/unique-paths-ii/",
  },
  {
    title: "Minimum Path Sum",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Matrix"],
    link: "https://leetcode.com/problems/minimum-path-sum/",
  },
  {
    title: "Simplify Path",
    difficulty: "Medium",
    topic: ["String", "Stack"],
    link: "https://leetcode.com/problems/simplify-path/",
  },
  {
    title: "Edit Distance",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/edit-distance/",
  },
  {
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Matrix"],
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
  },
  {
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    topic: ["Array", "Binary Search", "Matrix"],
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
  },
  {
    title: "Sort Colors",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Sorting"],
    link: "https://leetcode.com/problems/sort-colors/",
  },
  {
    title: "Combinations",
    difficulty: "Medium",
    topic: ["Backtracking"],
    link: "https://leetcode.com/problems/combinations/",
  },
  {
    title: "Subsets",
    difficulty: "Medium",
    topic: ["Array", "Backtracking", "Bit Manipulation"],
    link: "https://leetcode.com/problems/subsets/",
  },
  {
    title: "Word Search",
    difficulty: "Medium",
    topic: ["Array", "String", "Backtracking", "Depth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/word-search/",
  },
  {
    title: "Remove Duplicates from Sorted Array II",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers"],
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/",
  },
  {
    title: "Search in Rotated Sorted Array II",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
  },
  {
    title: "Remove Duplicates from Sorted List II",
    difficulty: "Medium",
    topic: ["Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/",
  },
  {
    title: "Partition List",
    difficulty: "Medium",
    topic: ["Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/partition-list/",
  },
  {
    title: "Gray Code",
    difficulty: "Medium",
    topic: ["Math", "Backtracking", "Bit Manipulation"],
    link: "https://leetcode.com/problems/gray-code/",
  },
  {
    title: "Subsets II",
    difficulty: "Medium",
    topic: ["Array", "Backtracking", "Bit Manipulation"],
    link: "https://leetcode.com/problems/subsets-ii/",
  },
  {
    title: "Decode Ways",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/decode-ways/",
  },
  {
    title: "Reverse Linked List II",
    difficulty: "Medium",
    topic: ["Linked List"],
    link: "https://leetcode.com/problems/reverse-linked-list-ii/",
  },
  {
    title: "Restore IP Addresses",
    difficulty: "Medium",
    topic: ["String", "Backtracking"],
    link: "https://leetcode.com/problems/restore-ip-addresses/",
  },
  {
    title: "Unique Binary Search Trees II",
    difficulty: "Medium",
    topic: [
      "Dynamic Programming",
      "Backtracking",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/unique-binary-search-trees-ii/",
  },
  {
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    topic: [
      "Math",
      "Dynamic Programming",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/unique-binary-search-trees/",
  },
  {
    title: "Interleaving String",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/interleaving-string/",
  },
  {
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    title: "Recover Binary Search Tree",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/recover-binary-search-tree/",
  },
  {
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    topic: ["Tree", "Breadth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  },
  {
    title: "Binary Tree Zigzag Level Order Traversal",
    difficulty: "Medium",
    topic: ["Tree", "Breadth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
  },
  {
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  },
  {
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
  },
  {
    title: "Binary Tree Level Order Traversal II",
    difficulty: "Medium",
    topic: ["Tree", "Breadth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/",
  },
  {
    title: "Convert Sorted List to Binary Search Tree",
    difficulty: "Medium",
    topic: [
      "Linked List",
      "Divide and Conquer",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/",
  },
  {
    title: "Path Sum II",
    difficulty: "Medium",
    topic: ["Backtracking", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/path-sum-ii/",
  },
  {
    title: "Flatten Binary Tree to Linked List",
    difficulty: "Medium",
    topic: [
      "Linked List",
      "Stack",
      "Tree",
      "Depth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
  },
  {
    title: "Populating Next Right Pointers in Each Node",
    difficulty: "Medium",
    topic: [
      "Linked List",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
  },
  {
    title: "Populating Next Right Pointers in Each Node II",
    difficulty: "Medium",
    topic: [
      "Linked List",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/",
  },
  {
    title: "Triangle",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/triangle/",
  },
  {
    title: "Best Time to Buy and Sell Stock II",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Greedy"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
  },
  {
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Union Find"],
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
  {
    title: "Sum Root to Leaf Numbers",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
  },
  {
    title: "Surrounded Regions",
    difficulty: "Medium",
    topic: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    link: "https://leetcode.com/problems/surrounded-regions/",
  },
  {
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming", "Backtracking"],
    link: "https://leetcode.com/problems/palindrome-partitioning/",
  },
  {
    title: "Clone Graph",
    difficulty: "Medium",
    topic: [
      "Hash Table",
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
    ],
    link: "https://leetcode.com/problems/clone-graph/",
  },
  {
    title: "Gas Station",
    difficulty: "Medium",
    topic: ["Array", "Greedy"],
    link: "https://leetcode.com/problems/gas-station/",
  },
  {
    title: "Single Number II",
    difficulty: "Medium",
    topic: ["Array", "Bit Manipulation"],
    link: "https://leetcode.com/problems/single-number-ii/",
  },
  {
    title: "Copy List with Random Pointer",
    difficulty: "Medium",
    topic: ["Hash Table", "Linked List"],
    link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
  },
  {
    title: "Word Break",
    difficulty: "Medium",
    topic: [
      "Array",
      "Hash Table",
      "String",
      "Dynamic Programming",
      "Trie",
      "Memoization",
    ],
    link: "https://leetcode.com/problems/word-break/",
  },
  {
    title: "Linked List Cycle II",
    difficulty: "Medium",
    topic: ["Hash Table", "Linked List", "Two Pointers"],
    link: "https://leetcode.com/problems/linked-list-cycle-ii/",
  },
  {
    title: "Reorder List",
    difficulty: "Medium",
    topic: ["Linked List", "Two Pointers", "Stack", "Recursion"],
    link: "https://leetcode.com/problems/reorder-list/",
  },
  {
    title: "LRU Cache",
    difficulty: "Medium",
    topic: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    link: "https://leetcode.com/problems/lru-cache/",
  },
  {
    title: "Insertion Sort List",
    difficulty: "Medium",
    topic: ["Linked List", "Sorting"],
    link: "https://leetcode.com/problems/insertion-sort-list/",
  },
  {
    title: "Sort List",
    difficulty: "Medium",
    topic: [
      "Linked List",
      "Two Pointers",
      "Divide and Conquer",
      "Sorting",
      "Merge Sort",
    ],
    link: "https://leetcode.com/problems/sort-list/",
  },
  {
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    topic: ["Array", "Math", "Stack"],
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
  },
  {
    title: "Reverse Words in a String",
    difficulty: "Medium",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/reverse-words-in-a-string/",
  },
  {
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/maximum-product-subarray/",
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  },
  {
    title: "Min Stack",
    difficulty: "Medium",
    topic: ["Stack", "Design"],
    link: "https://leetcode.com/problems/min-stack/",
  },
  {
    title: "Find Peak Element",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/find-peak-element/",
  },
  {
    title: "Maximum Gap",
    difficulty: "Medium",
    topic: ["Array", "Sorting", "Bucket Sort", "Radix Sort"],
    link: "https://leetcode.com/problems/maximum-gap/",
  },
  {
    title: "Compare Version Numbers",
    difficulty: "Medium",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/compare-version-numbers/",
  },
  {
    title: "Fraction to Recurring Decimal",
    difficulty: "Medium",
    topic: ["Hash Table", "Math", "String"],
    link: "https://leetcode.com/problems/fraction-to-recurring-decimal/",
  },
  {
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Binary Search"],
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  },
  {
    title: "Factorial Trailing Zeroes",
    difficulty: "Medium",
    topic: ["Math"],
    link: "https://leetcode.com/problems/factorial-trailing-zeroes/",
  },
  {
    title: "Binary Search Tree Iterator",
    difficulty: "Medium",
    topic: [
      "Stack",
      "Tree",
      "Design",
      "Binary Search Tree",
      "Binary Tree",
      "Iterator",
    ],
    link: "https://leetcode.com/problems/binary-search-tree-iterator/",
  },
  {
    title: "Second Highest Salary",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/second-highest-salary/",
  },
  {
    title: "Nth Highest Salary",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/nth-highest-salary/",
  },
  {
    title: "Rank Scores",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/rank-scores/",
  },
  {
    title: "Largest Number",
    difficulty: "Medium",
    topic: ["Array", "String", "Greedy", "Sorting"],
    link: "https://leetcode.com/problems/largest-number/",
  },
  {
    title: "Consecutive Numbers",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/consecutive-numbers/",
  },
  {
    title: "Department Highest Salary",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/department-highest-salary/",
  },
  {
    title: "Repeated DNA Sequences",
    difficulty: "Medium",
    topic: [
      "Hash Table",
      "String",
      "Bit Manipulation",
      "Sliding Window",
      "Rolling Hash",
      "Hash Function",
    ],
    link: "https://leetcode.com/problems/repeated-dna-sequences/",
  },
  {
    title: "Rotate Array",
    difficulty: "Medium",
    topic: ["Array", "Math", "Two Pointers"],
    link: "https://leetcode.com/problems/rotate-array/",
  },
  {
    title: "Word Frequency",
    difficulty: "Medium",
    topic: ["Shell"],
    link: "https://leetcode.com/problems/word-frequency/",
  },
  {
    title: "Transpose File",
    difficulty: "Medium",
    topic: ["Shell"],
    link: "https://leetcode.com/problems/transpose-file/",
  },
  {
    title: "House Robber",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/house-robber/",
  },
  {
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    title: "Number of Islands",
    difficulty: "Medium",
    topic: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    link: "https://leetcode.com/problems/number-of-islands/",
  },
  {
    title: "Bitwise AND of Numbers Range",
    difficulty: "Medium",
    topic: ["Bit Manipulation"],
    link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/",
  },
  {
    title: "Count Primes",
    difficulty: "Medium",
    topic: ["Array", "Math", "Enumeration", "Number Theory"],
    link: "https://leetcode.com/problems/count-primes/",
  },
  {
    title: "Course Schedule",
    difficulty: "Medium",
    topic: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    link: "https://leetcode.com/problems/course-schedule/",
  },
  {
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Design", "Trie"],
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
  },
  {
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    topic: ["Array", "Binary Search", "Sliding Window", "Prefix Sum"],
    link: "https://leetcode.com/problems/minimum-size-subarray-sum/",
  },
  {
    title: "Course Schedule II",
    difficulty: "Medium",
    topic: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    link: "https://leetcode.com/problems/course-schedule-ii/",
  },
  {
    title: "Design Add and Search Words Data Structure",
    difficulty: "Medium",
    topic: ["String", "Depth-First Search", "Design", "Trie"],
    link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
  },
  {
    title: "House Robber II",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/house-robber-ii/",
  },
  {
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    topic: [
      "Array",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Quickselect",
    ],
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  },
  {
    title: "Combination Sum III",
    difficulty: "Medium",
    topic: ["Array", "Backtracking"],
    link: "https://leetcode.com/problems/combination-sum-iii/",
  },
  {
    title: "Maximal Square",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Matrix"],
    link: "https://leetcode.com/problems/maximal-square/",
  },
  {
    title: "Rectangle Area",
    difficulty: "Medium",
    topic: ["Math", "Geometry"],
    link: "https://leetcode.com/problems/rectangle-area/",
  },
  {
    title: "Basic Calculator II",
    difficulty: "Medium",
    topic: ["Math", "String", "Stack"],
    link: "https://leetcode.com/problems/basic-calculator-ii/",
  },
  {
    title: "Majority Element II",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Sorting", "Counting"],
    link: "https://leetcode.com/problems/majority-element-ii/",
  },
  {
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  },
  {
    title: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  },
  {
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
  },
  {
    title: "Delete Node in a Linked List",
    difficulty: "Medium",
    topic: ["Linked List"],
    link: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
  },
  {
    title: "Product of Array Except Self",
    difficulty: "Medium",
    topic: ["Array", "Prefix Sum"],
    link: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    topic: ["Array", "Binary Search", "Divide and Conquer", "Matrix"],
    link: "https://leetcode.com/problems/search-a-2d-matrix-ii/",
  },
  {
    title: "Different Ways to Add Parentheses",
    difficulty: "Medium",
    topic: [
      "Math",
      "String",
      "Dynamic Programming",
      "Recursion",
      "Memoization",
    ],
    link: "https://leetcode.com/problems/different-ways-to-add-parentheses/",
  },
  {
    title: "Single Number III",
    difficulty: "Medium",
    topic: ["Array", "Bit Manipulation"],
    link: "https://leetcode.com/problems/single-number-iii/",
  },
  {
    title: "Ugly Number II",
    difficulty: "Medium",
    topic: [
      "Hash Table",
      "Math",
      "Dynamic Programming",
      "Heap (Priority Queue)",
    ],
    link: "https://leetcode.com/problems/ugly-number-ii/",
  },
  {
    title: "H-Index",
    difficulty: "Medium",
    topic: ["Array", "Sorting", "Counting Sort"],
    link: "https://leetcode.com/problems/h-index/",
  },
  {
    title: "H-Index II",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/h-index-ii/",
  },
  {
    title: "Perfect Squares",
    difficulty: "Medium",
    topic: ["Math", "Dynamic Programming", "Breadth-First Search"],
    link: "https://leetcode.com/problems/perfect-squares/",
  },
  {
    title: "Peeking Iterator",
    difficulty: "Medium",
    topic: ["Array", "Design", "Iterator"],
    link: "https://leetcode.com/problems/peeking-iterator/",
  },
  {
    title: "Find the Duplicate Number",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"],
    link: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    title: "Game of Life",
    difficulty: "Medium",
    topic: ["Array", "Matrix", "Simulation"],
    link: "https://leetcode.com/problems/game-of-life/",
  },
  {
    title: "Bulls and Cows",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Counting"],
    link: "https://leetcode.com/problems/bulls-and-cows/",
  },
  {
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topic: ["Array", "Binary Search", "Dynamic Programming"],
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
  },
  {
    title: "Range Sum Query 2D - Immutable",
    difficulty: "Medium",
    topic: ["Array", "Design", "Matrix", "Prefix Sum"],
    link: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
  },
  {
    title: "Additive Number",
    difficulty: "Medium",
    topic: ["String", "Backtracking"],
    link: "https://leetcode.com/problems/additive-number/",
  },
  {
    title: "Range Sum Query - Mutable",
    difficulty: "Medium",
    topic: ["Array", "Design", "Binary Indexed Tree", "Segment Tree"],
    link: "https://leetcode.com/problems/range-sum-query-mutable/",
  },
  {
    title: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  },
  {
    title: "Minimum Height Trees",
    difficulty: "Medium",
    topic: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    link: "https://leetcode.com/problems/minimum-height-trees/",
  },
  {
    title: "Super Ugly Number",
    difficulty: "Medium",
    topic: ["Array", "Math", "Dynamic Programming"],
    link: "https://leetcode.com/problems/super-ugly-number/",
  },
  {
    title: "Remove Duplicate Letters",
    difficulty: "Medium",
    topic: ["String", "Stack", "Greedy", "Monotonic Stack"],
    link: "https://leetcode.com/problems/remove-duplicate-letters/",
  },
  {
    title: "Maximum Product of Word Lengths",
    difficulty: "Medium",
    topic: ["Array", "String", "Bit Manipulation"],
    link: "https://leetcode.com/problems/maximum-product-of-word-lengths/",
  },
  {
    title: "Bulb Switcher",
    difficulty: "Medium",
    topic: ["Math", "Brainteaser"],
    link: "https://leetcode.com/problems/bulb-switcher/",
  },
  {
    title: "Coin Change",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Breadth-First Search"],
    link: "https://leetcode.com/problems/coin-change/",
  },
  {
    title: "Wiggle Sort II",
    difficulty: "Medium",
    topic: ["Array", "Divide and Conquer", "Greedy", "Sorting", "Quickselect"],
    link: "https://leetcode.com/problems/wiggle-sort-ii/",
  },
  {
    title: "Odd Even Linked List",
    difficulty: "Medium",
    topic: ["Linked List"],
    link: "https://leetcode.com/problems/odd-even-linked-list/",
  },
  {
    title: "Verify Preorder Serialization of a Binary Tree",
    difficulty: "Medium",
    topic: ["String", "Stack", "Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/",
  },
  {
    title: "Increasing Triplet Subsequence",
    difficulty: "Medium",
    topic: ["Array", "Greedy"],
    link: "https://leetcode.com/problems/increasing-triplet-subsequence/",
  },
  {
    title: "House Robber III",
    difficulty: "Medium",
    topic: ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/house-robber-iii/",
  },
  {
    title: "Flatten Nested List Iterator",
    difficulty: "Medium",
    topic: [
      "Stack",
      "Tree",
      "Depth-First Search",
      "Design",
      "Queue",
      "Iterator",
    ],
    link: "https://leetcode.com/problems/flatten-nested-list-iterator/",
  },
  {
    title: "Integer Break",
    difficulty: "Medium",
    topic: ["Math", "Dynamic Programming"],
    link: "https://leetcode.com/problems/integer-break/",
  },
  {
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topic: [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect",
    ],
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
  },
  {
    title: "Design Twitter",
    difficulty: "Medium",
    topic: ["Hash Table", "Linked List", "Design", "Heap (Priority Queue)"],
    link: "https://leetcode.com/problems/design-twitter/",
  },
  {
    title: "Count Numbers with Unique Digits",
    difficulty: "Medium",
    topic: ["Math", "Dynamic Programming", "Backtracking"],
    link: "https://leetcode.com/problems/count-numbers-with-unique-digits/",
  },
  {
    title: "Water and Jug Problem",
    difficulty: "Medium",
    topic: ["Math", "Depth-First Search", "Breadth-First Search"],
    link: "https://leetcode.com/problems/water-and-jug-problem/",
  },
  {
    title: "Largest Divisible Subset",
    difficulty: "Medium",
    topic: ["Array", "Math", "Dynamic Programming", "Sorting"],
    link: "https://leetcode.com/problems/largest-divisible-subset/",
  },
  {
    title: "Sum of Two Integers",
    difficulty: "Medium",
    topic: ["Math", "Bit Manipulation"],
    link: "https://leetcode.com/problems/sum-of-two-integers/",
  },
  {
    title: "Super Pow",
    difficulty: "Medium",
    topic: ["Math", "Divide and Conquer"],
    link: "https://leetcode.com/problems/super-pow/",
  },
  {
    title: "Find K Pairs with Smallest Sums",
    difficulty: "Medium",
    topic: ["Array", "Heap (Priority Queue)"],
    link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
  },
  {
    title: "Guess Number Higher or Lower II",
    difficulty: "Medium",
    topic: ["Math", "Dynamic Programming", "Game Theory"],
    link: "https://leetcode.com/problems/guess-number-higher-or-lower-ii/",
  },
  {
    title: "Wiggle Subsequence",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Greedy"],
    link: "https://leetcode.com/problems/wiggle-subsequence/",
  },
  {
    title: "Combination Sum IV",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/combination-sum-iv/",
  },
  {
    title: "Kth Smallest Element in a Sorted Matrix",
    difficulty: "Medium",
    topic: [
      "Array",
      "Binary Search",
      "Sorting",
      "Heap (Priority Queue)",
      "Matrix",
    ],
    link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
  },
  {
    title: "Insert Delete GetRandom O(1)",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Math", "Design", "Randomized"],
    link: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
  },
  {
    title: "Linked List Random Node",
    difficulty: "Medium",
    topic: ["Linked List", "Math", "Reservoir Sampling", "Randomized"],
    link: "https://leetcode.com/problems/linked-list-random-node/",
  },
  {
    title: "Shuffle an Array",
    difficulty: "Medium",
    topic: ["Array", "Math", "Design", "Randomized"],
    link: "https://leetcode.com/problems/shuffle-an-array/",
  },
  {
    title: "Mini Parser",
    difficulty: "Medium",
    topic: ["String", "Stack", "Depth-First Search"],
    link: "https://leetcode.com/problems/mini-parser/",
  },
  {
    title: "Lexicographical Numbers",
    difficulty: "Medium",
    topic: ["Depth-First Search", "Trie"],
    link: "https://leetcode.com/problems/lexicographical-numbers/",
  },
  {
    title: "Longest Absolute File Path",
    difficulty: "Medium",
    topic: ["String", "Stack", "Depth-First Search"],
    link: "https://leetcode.com/problems/longest-absolute-file-path/",
  },
  {
    title: "Elimination Game",
    difficulty: "Medium",
    topic: ["Math", "Recursion"],
    link: "https://leetcode.com/problems/elimination-game/",
  },
  {
    title: "UTF-8 Validation",
    difficulty: "Medium",
    topic: ["Array", "Bit Manipulation"],
    link: "https://leetcode.com/problems/utf-8-validation/",
  },
  {
    title: "Decode String",
    difficulty: "Medium",
    topic: ["String", "Stack", "Recursion"],
    link: "https://leetcode.com/problems/decode-string/",
  },
  {
    title: "Longest Substring with At Least K Repeating Characters",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Divide and Conquer", "Sliding Window"],
    link: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/",
  },
  {
    title: "Rotate Function",
    difficulty: "Medium",
    topic: ["Array", "Math", "Dynamic Programming"],
    link: "https://leetcode.com/problems/rotate-function/",
  },
  {
    title: "Integer Replacement",
    difficulty: "Medium",
    topic: ["Dynamic Programming", "Greedy", "Bit Manipulation", "Memoization"],
    link: "https://leetcode.com/problems/integer-replacement/",
  },
  {
    title: "Random Pick Index",
    difficulty: "Medium",
    topic: ["Hash Table", "Math", "Reservoir Sampling", "Randomized"],
    link: "https://leetcode.com/problems/random-pick-index/",
  },
  {
    title: "Evaluate Division",
    difficulty: "Medium",
    topic: [
      "Array",
      "String",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Graph",
      "Shortest Path",
    ],
    link: "https://leetcode.com/problems/evaluate-division/",
  },
  {
    title: "Nth Digit",
    difficulty: "Medium",
    topic: ["Math", "Binary Search"],
    link: "https://leetcode.com/problems/nth-digit/",
  },
  {
    title: "Remove K Digits",
    difficulty: "Medium",
    topic: ["String", "Stack", "Greedy", "Monotonic Stack"],
    link: "https://leetcode.com/problems/remove-k-digits/",
  },
  {
    title: "Queue Reconstruction by Height",
    difficulty: "Medium",
    topic: ["Array", "Binary Indexed Tree", "Segment Tree", "Sorting"],
    link: "https://leetcode.com/problems/queue-reconstruction-by-height/",
  },
  {
    title: "Arithmetic Slices",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Sliding Window"],
    link: "https://leetcode.com/problems/arithmetic-slices/",
  },
  {
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
  },
  {
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    topic: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
  },
  {
    title: "Battleships in a Board",
    difficulty: "Medium",
    topic: ["Array", "Depth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/battleships-in-a-board/",
  },
  {
    title: "Maximum XOR of Two Numbers in an Array",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Bit Manipulation", "Trie"],
    link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
  },
  {
    title: "Reconstruct Original Digits from English",
    difficulty: "Medium",
    topic: ["Hash Table", "Math", "String"],
    link: "https://leetcode.com/problems/reconstruct-original-digits-from-english/",
  },
  {
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    title: "Construct Quad Tree",
    difficulty: "Medium",
    topic: ["Array", "Divide and Conquer", "Tree", "Matrix"],
    link: "https://leetcode.com/problems/construct-quad-tree/",
  },
  {
    title: "N-ary Tree Level Order Traversal",
    difficulty: "Medium",
    topic: ["Tree", "Breadth-First Search"],
    link: "https://leetcode.com/problems/n-ary-tree-level-order-traversal/",
  },
  {
    title: "Flatten a Multilevel Doubly Linked List",
    difficulty: "Medium",
    topic: ["Linked List", "Depth-First Search", "Doubly-Linked List"],
    link: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
  },
  {
    title: "Minimum Genetic Mutation",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Breadth-First Search"],
    link: "https://leetcode.com/problems/minimum-genetic-mutation/",
  },
  {
    title: "Non-overlapping Intervals",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Greedy", "Sorting"],
    link: "https://leetcode.com/problems/non-overlapping-intervals/",
  },
  {
    title: "Path Sum III",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/path-sum-iii/",
  },
  {
    title: "Find All Anagrams in a String",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
  },
  {
    title: "Find All Duplicates in an Array",
    difficulty: "Medium",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
  },
  {
    title: "String Compression",
    difficulty: "Medium",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/string-compression/",
  },
  {
    title: "Add Two Numbers II",
    difficulty: "Medium",
    topic: ["Linked List", "Math", "Stack"],
    link: "https://leetcode.com/problems/add-two-numbers-ii/",
  },
  {
    title: "Number of Boomerangs",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Math"],
    link: "https://leetcode.com/problems/number-of-boomerangs/",
  },
  {
    title: "Serialize and Deserialize BST",
    difficulty: "Medium",
    topic: [
      "String",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Design",
      "Binary Search Tree",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/serialize-and-deserialize-bst/",
  },
  {
    title: "Delete Node in a BST",
    difficulty: "Medium",
    topic: ["Tree", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/delete-node-in-a-bst/",
  },
  {
    title: "Sort Characters By Frequency",
    difficulty: "Medium",
    topic: [
      "Hash Table",
      "String",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
    ],
    link: "https://leetcode.com/problems/sort-characters-by-frequency/",
  },
  {
    title: "Minimum Number of Arrows to Burst Balloons",
    difficulty: "Medium",
    topic: ["Array", "Greedy", "Sorting"],
    link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
  },
  {
    title: "Minimum Moves to Equal Array Elements",
    difficulty: "Medium",
    topic: ["Array", "Math"],
    link: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements/",
  },
  {
    title: "4Sum II",
    difficulty: "Medium",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/4sum-ii/",
  },
  {
    title: "132 Pattern",
    difficulty: "Medium",
    topic: [
      "Array",
      "Binary Search",
      "Stack",
      "Monotonic Stack",
      "Ordered Set",
    ],
    link: "https://leetcode.com/problems/132-pattern/",
  },
  {
    title: "Circular Array Loop",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Two Pointers"],
    link: "https://leetcode.com/problems/circular-array-loop/",
  },
  {
    title: "Minimum Moves to Equal Array Elements II",
    difficulty: "Medium",
    topic: ["Array", "Math", "Sorting"],
    link: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements-ii/",
  },
  {
    title: "Can I Win",
    difficulty: "Medium",
    topic: [
      "Math",
      "Dynamic Programming",
      "Bit Manipulation",
      "Memoization",
      "Game Theory",
      "Bitmask",
    ],
    link: "https://leetcode.com/problems/can-i-win/",
  },
  {
    title: "Unique Substrings in Wraparound String",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/unique-substrings-in-wraparound-string/",
  },
  {
    title: "Validate IP Address",
    difficulty: "Medium",
    topic: ["String"],
    link: "https://leetcode.com/problems/validate-ip-address/",
  },
  {
    title: "Implement Rand10() Using Rand7()",
    difficulty: "Medium",
    topic: [
      "Math",
      "Rejection Sampling",
      "Randomized",
      "Probability and Statistics",
    ],
    link: "https://leetcode.com/problems/implement-rand10-using-rand7/",
  },
  {
    title: "Matchsticks to Square",
    difficulty: "Medium",
    topic: [
      "Array",
      "Dynamic Programming",
      "Backtracking",
      "Bit Manipulation",
      "Bitmask",
    ],
    link: "https://leetcode.com/problems/matchsticks-to-square/",
  },
  {
    title: "Ones and Zeroes",
    difficulty: "Medium",
    topic: ["Array", "String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/ones-and-zeroes/",
  },
  {
    title: "Heaters",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Binary Search", "Sorting"],
    link: "https://leetcode.com/problems/heaters/",
  },
  {
    title: "Total Hamming Distance",
    difficulty: "Medium",
    topic: ["Array", "Math", "Bit Manipulation"],
    link: "https://leetcode.com/problems/total-hamming-distance/",
  },
  {
    title: "Generate Random Point in a Circle",
    difficulty: "Medium",
    topic: ["Math", "Geometry", "Rejection Sampling", "Randomized"],
    link: "https://leetcode.com/problems/generate-random-point-in-a-circle/",
  },
  {
    title: "Magical String",
    difficulty: "Medium",
    topic: ["Two Pointers", "String"],
    link: "https://leetcode.com/problems/magical-string/",
  },
  {
    title: "Predict the Winner",
    difficulty: "Medium",
    topic: ["Array", "Math", "Dynamic Programming", "Recursion", "Game Theory"],
    link: "https://leetcode.com/problems/predict-the-winner/",
  },
  {
    title: "Non-decreasing Subsequences",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Backtracking", "Bit Manipulation"],
    link: "https://leetcode.com/problems/non-decreasing-subsequences/",
  },
  {
    title: "Target Sum",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Backtracking"],
    link: "https://leetcode.com/problems/target-sum/",
  },
  {
    title: "Random Point in Non-overlapping Rectangles",
    difficulty: "Medium",
    topic: [
      "Array",
      "Math",
      "Binary Search",
      "Reservoir Sampling",
      "Prefix Sum",
      "Ordered Set",
      "Randomized",
    ],
    link: "https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/",
  },
  {
    title: "Diagonal Traverse",
    difficulty: "Medium",
    topic: ["Array", "Matrix", "Simulation"],
    link: "https://leetcode.com/problems/diagonal-traverse/",
  },
  {
    title: "Next Greater Element II",
    difficulty: "Medium",
    topic: ["Array", "Stack", "Monotonic Stack"],
    link: "https://leetcode.com/problems/next-greater-element-ii/",
  },
  {
    title: "Most Frequent Subtree Sum",
    difficulty: "Medium",
    topic: ["Hash Table", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/most-frequent-subtree-sum/",
  },
  {
    title: "Find Bottom Left Tree Value",
    difficulty: "Medium",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/find-bottom-left-tree-value/",
  },
  {
    title: "Find Largest Value in Each Tree Row",
    difficulty: "Medium",
    topic: [
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/find-largest-value-in-each-tree-row/",
  },
  {
    title: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/longest-palindromic-subsequence/",
  },
  {
    title: "Coin Change II",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/coin-change-ii/",
  },
  {
    title: "Random Flip Matrix",
    difficulty: "Medium",
    topic: ["Hash Table", "Math", "Reservoir Sampling", "Randomized"],
    link: "https://leetcode.com/problems/random-flip-matrix/",
  },
  {
    title: "Longest Uncommon Subsequence II",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Two Pointers", "String", "Sorting"],
    link: "https://leetcode.com/problems/longest-uncommon-subsequence-ii/",
  },
  {
    title: "Continuous Subarray Sum",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Math", "Prefix Sum"],
    link: "https://leetcode.com/problems/continuous-subarray-sum/",
  },
  {
    title: "Longest Word in Dictionary through Deleting",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "String", "Sorting"],
    link: "https://leetcode.com/problems/longest-word-in-dictionary-through-deleting/",
  },
  {
    title: "Contiguous Array",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Prefix Sum"],
    link: "https://leetcode.com/problems/contiguous-array/",
  },
  {
    title: "Beautiful Arrangement",
    difficulty: "Medium",
    topic: [
      "Array",
      "Dynamic Programming",
      "Backtracking",
      "Bit Manipulation",
      "Bitmask",
    ],
    link: "https://leetcode.com/problems/beautiful-arrangement/",
  },
  {
    title: "Random Pick with Weight",
    difficulty: "Medium",
    topic: ["Array", "Math", "Binary Search", "Prefix Sum", "Randomized"],
    link: "https://leetcode.com/problems/random-pick-with-weight/",
  },
  {
    title: "Minesweeper",
    difficulty: "Medium",
    topic: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/minesweeper/",
  },
  {
    title: "K-diff Pairs in an Array",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Two Pointers", "Binary Search", "Sorting"],
    link: "https://leetcode.com/problems/k-diff-pairs-in-an-array/",
  },
  {
    title: "Encode and Decode TinyURL",
    difficulty: "Medium",
    topic: ["Hash Table", "String", "Design", "Hash Function"],
    link: "https://leetcode.com/problems/encode-and-decode-tinyurl/",
  },
  {
    title: "Complex Number Multiplication",
    difficulty: "Medium",
    topic: ["Math", "String", "Simulation"],
    link: "https://leetcode.com/problems/complex-number-multiplication/",
  },
  {
    title: "Convert BST to Greater Tree",
    difficulty: "Medium",
    topic: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    link: "https://leetcode.com/problems/convert-bst-to-greater-tree/",
  },
  {
    title: "Minimum Time Difference",
    difficulty: "Medium",
    topic: ["Array", "Math", "String", "Sorting"],
    link: "https://leetcode.com/problems/minimum-time-difference/",
  },
  {
    title: "Single Element in a Sorted Array",
    difficulty: "Medium",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
  },
  {
    title: "01 Matrix",
    difficulty: "Medium",
    topic: ["Array", "Dynamic Programming", "Breadth-First Search", "Matrix"],
    link: "https://leetcode.com/problems/01-matrix/",
  },
  {
    title: "Number of Provinces",
    difficulty: "Medium",
    topic: [
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Graph",
    ],
    link: "https://leetcode.com/problems/number-of-provinces/",
  },
  {
    title: "Game Play Analysis IV",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/game-play-analysis-iv/",
  },
  {
    title: "Optimal Division",
    difficulty: "Medium",
    topic: ["Array", "Math", "Dynamic Programming"],
    link: "https://leetcode.com/problems/optimal-division/",
  },
  {
    title: "Brick Wall",
    difficulty: "Medium",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/brick-wall/",
  },
  {
    title: "Next Greater Element III",
    difficulty: "Medium",
    topic: ["Math", "Two Pointers", "String"],
    link: "https://leetcode.com/problems/next-greater-element-iii/",
  },
  {
    title: "Logical OR of Two Binary Grids Represented as Quad-Trees",
    difficulty: "Medium",
    topic: ["Divide and Conquer", "Tree"],
    link: "https://leetcode.com/problems/logical-or-of-two-binary-grids-represented-as-quad-trees/",
  },
  {
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "Prefix Sum"],
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
  },
  {
    title: "Array Nesting",
    difficulty: "Medium",
    topic: ["Array", "Depth-First Search"],
    link: "https://leetcode.com/problems/array-nesting/",
  },
  {
    title: "Permutation in String",
    difficulty: "Medium",
    topic: ["Hash Table", "Two Pointers", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/permutation-in-string/",
  },
  {
    title: "Managers with at Least 5 Direct Reports",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/managers-with-at-least-5-direct-reports/",
  },
  {
    title: "Out of Boundary Paths",
    difficulty: "Medium",
    topic: ["Dynamic Programming"],
    link: "https://leetcode.com/problems/out-of-boundary-paths/",
  },
  {
    title: "Shortest Unsorted Continuous Subarray",
    difficulty: "Medium",
    topic: [
      "Array",
      "Two Pointers",
      "Stack",
      "Greedy",
      "Sorting",
      "Monotonic Stack",
    ],
    link: "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/",
  },
  {
    title: "Delete Operation for Two Strings",
    difficulty: "Medium",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/delete-operation-for-two-strings/",
  },
  {
    title: "Investments in 2016",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/investments-in-2016/",
  },
  {
    title: "Fraction Addition and Subtraction",
    difficulty: "Medium",
    topic: ["Math", "String", "Simulation"],
    link: "https://leetcode.com/problems/fraction-addition-and-subtraction/",
  },
  {
    title: "Valid Square",
    difficulty: "Medium",
    topic: ["Math", "Geometry"],
    link: "https://leetcode.com/problems/valid-square/",
  },
  {
    title: "Friend Requests II: Who Has the Most Friends",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends/",
  },
  {
    title: "Construct String from Binary Tree",
    difficulty: "Medium",
    topic: ["String", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/construct-string-from-binary-tree/",
  },
  {
    title: "Tree Node",
    difficulty: "Medium",
    topic: ["Database"],
    link: "https://leetcode.com/problems/tree-node/",
  },
  {
    title: "Find Duplicate File in System",
    difficulty: "Medium",
    topic: ["Array", "Hash Table", "String"],
    link: "https://leetcode.com/problems/find-duplicate-file-in-system/",
  },
  {
    title: "Valid Triangle Number",
    difficulty: "Medium",
    topic: ["Array", "Two Pointers", "Binary Search", "Greedy", "Sorting"],
    link: "https://leetcode.com/problems/valid-triangle-number/",
  },
  {
    title: "Task Scheduler",
    difficulty: "Medium",
    topic: [
      "Array",
      "Hash Table",
      "Greedy",
      "Sorting",
      "Heap (Priority Queue)",
      "Counting",
    ],
    link: "https://leetcode.com/problems/task-scheduler/",
  },
  {
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    topic: ["Array", "Binary Search", "Divide and Conquer"],
    link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
  },
  {
    title: "Regular Expression Matching",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming", "Recursion"],
    link: "https://leetcode.com/problems/regular-expression-matching/",
  },
  {
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    topic: [
      "Linked List",
      "Divide and Conquer",
      "Heap (Priority Queue)",
      "Merge Sort",
    ],
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
  },
  {
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    topic: ["Linked List", "Recursion"],
    link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  },
  {
    title: "Substring with Concatenation of All Words",
    difficulty: "Hard",
    topic: ["Hash Table", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
  },
  {
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming", "Stack"],
    link: "https://leetcode.com/problems/longest-valid-parentheses/",
  },
  {
    title: "Sudoku Solver",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "Backtracking", "Matrix"],
    link: "https://leetcode.com/problems/sudoku-solver/",
  },
  {
    title: "First Missing Positive",
    difficulty: "Hard",
    topic: ["Array", "Hash Table"],
    link: "https://leetcode.com/problems/first-missing-positive/",
  },
  {
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topic: [
      "Array",
      "Two Pointers",
      "Dynamic Programming",
      "Stack",
      "Monotonic Stack",
    ],
    link: "https://leetcode.com/problems/trapping-rain-water/",
  },
  {
    title: "Wildcard Matching",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming", "Greedy", "Recursion"],
    link: "https://leetcode.com/problems/wildcard-matching/",
  },
  {
    title: "N-Queens",
    difficulty: "Hard",
    topic: ["Array", "Backtracking"],
    link: "https://leetcode.com/problems/n-queens/",
  },
  {
    title: "N-Queens II",
    difficulty: "Hard",
    topic: ["Backtracking"],
    link: "https://leetcode.com/problems/n-queens-ii/",
  },
  {
    title: "Permutation Sequence",
    difficulty: "Hard",
    topic: ["Math", "Recursion"],
    link: "https://leetcode.com/problems/permutation-sequence/",
  },
  {
    title: "Valid Number",
    difficulty: "Hard",
    topic: ["String"],
    link: "https://leetcode.com/problems/valid-number/",
  },
  {
    title: "Text Justification",
    difficulty: "Hard",
    topic: ["Array", "String", "Simulation"],
    link: "https://leetcode.com/problems/text-justification/",
  },
  {
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topic: ["Hash Table", "String", "Sliding Window"],
    link: "https://leetcode.com/problems/minimum-window-substring/",
  },
  {
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    topic: ["Array", "Stack", "Monotonic Stack"],
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
  },
  {
    title: "Maximal Rectangle",
    difficulty: "Hard",
    topic: [
      "Array",
      "Dynamic Programming",
      "Stack",
      "Matrix",
      "Monotonic Stack",
    ],
    link: "https://leetcode.com/problems/maximal-rectangle/",
  },
  {
    title: "Scramble String",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/scramble-string/",
  },
  {
    title: "Distinct Subsequences",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/distinct-subsequences/",
  },
  {
    title: "Best Time to Buy and Sell Stock III",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
  },
  {
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    topic: ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
    link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  },
  {
    title: "Word Ladder II",
    difficulty: "Hard",
    topic: ["Hash Table", "String", "Backtracking", "Breadth-First Search"],
    link: "https://leetcode.com/problems/word-ladder-ii/",
  },
  {
    title: "Word Ladder",
    difficulty: "Hard",
    topic: ["Hash Table", "String", "Breadth-First Search"],
    link: "https://leetcode.com/problems/word-ladder/",
  },
  {
    title: "Palindrome Partitioning II",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/palindrome-partitioning-ii/",
  },
  {
    title: "Candy",
    difficulty: "Hard",
    topic: ["Array", "Greedy"],
    link: "https://leetcode.com/problems/candy/",
  },
  {
    title: "Word Break II",
    difficulty: "Hard",
    topic: [
      "Array",
      "Hash Table",
      "String",
      "Dynamic Programming",
      "Backtracking",
      "Trie",
      "Memoization",
    ],
    link: "https://leetcode.com/problems/word-break-ii/",
  },
  {
    title: "Max Points on a Line",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "Math", "Geometry"],
    link: "https://leetcode.com/problems/max-points-on-a-line/",
  },
  {
    title: "Find Minimum in Rotated Sorted Array II",
    difficulty: "Hard",
    topic: ["Array", "Binary Search"],
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/",
  },
  {
    title: "Dungeon Game",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming", "Matrix"],
    link: "https://leetcode.com/problems/dungeon-game/",
  },
  {
    title: "Department Top Three Salaries",
    difficulty: "Hard",
    topic: ["Database"],
    link: "https://leetcode.com/problems/department-top-three-salaries/",
  },
  {
    title: "Best Time to Buy and Sell Stock IV",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
  },
  {
    title: "Word Search II",
    difficulty: "Hard",
    topic: ["Array", "String", "Backtracking", "Trie", "Matrix"],
    link: "https://leetcode.com/problems/word-search-ii/",
  },
  {
    title: "Shortest Palindrome",
    difficulty: "Hard",
    topic: ["String", "Rolling Hash", "String Matching", "Hash Function"],
    link: "https://leetcode.com/problems/shortest-palindrome/",
  },
  {
    title: "The Skyline Problem",
    difficulty: "Hard",
    topic: [
      "Array",
      "Divide and Conquer",
      "Binary Indexed Tree",
      "Segment Tree",
      "Line Sweep",
      "Heap (Priority Queue)",
      "Ordered Set",
    ],
    link: "https://leetcode.com/problems/the-skyline-problem/",
  },
  {
    title: "Contains Duplicate III",
    difficulty: "Hard",
    topic: ["Array", "Sliding Window", "Sorting", "Bucket Sort", "Ordered Set"],
    link: "https://leetcode.com/problems/contains-duplicate-iii/",
  },
  {
    title: "Basic Calculator",
    difficulty: "Hard",
    topic: ["Math", "String", "Stack", "Recursion"],
    link: "https://leetcode.com/problems/basic-calculator/",
  },
  {
    title: "Number of Digit One",
    difficulty: "Hard",
    topic: ["Math", "Dynamic Programming", "Recursion"],
    link: "https://leetcode.com/problems/number-of-digit-one/",
  },
  {
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    topic: [
      "Array",
      "Queue",
      "Sliding Window",
      "Heap (Priority Queue)",
      "Monotonic Queue",
    ],
    link: "https://leetcode.com/problems/sliding-window-maximum/",
  },
  {
    title: "Trips and Users",
    difficulty: "Hard",
    topic: ["Database"],
    link: "https://leetcode.com/problems/trips-and-users/",
  },
  {
    title: "Integer to English Words",
    difficulty: "Hard",
    topic: ["Math", "String", "Recursion"],
    link: "https://leetcode.com/problems/integer-to-english-words/",
  },
  {
    title: "Expression Add Operators",
    difficulty: "Hard",
    topic: ["Math", "String", "Backtracking"],
    link: "https://leetcode.com/problems/expression-add-operators/",
  },
  {
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    topic: [
      "Two Pointers",
      "Design",
      "Sorting",
      "Heap (Priority Queue)",
      "Data Stream",
    ],
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    topic: [
      "String",
      "Tree",
      "Depth-First Search",
      "Breadth-First Search",
      "Design",
      "Binary Tree",
    ],
    link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  },
  {
    title: "Remove Invalid Parentheses",
    difficulty: "Hard",
    topic: ["String", "Backtracking", "Breadth-First Search"],
    link: "https://leetcode.com/problems/remove-invalid-parentheses/",
  },
  {
    title: "Burst Balloons",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/burst-balloons/",
  },
  {
    title: "Count of Smaller Numbers After Self",
    difficulty: "Hard",
    topic: [
      "Array",
      "Binary Search",
      "Divide and Conquer",
      "Binary Indexed Tree",
      "Segment Tree",
      "Merge Sort",
      "Ordered Set",
    ],
    link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
  },
  {
    title: "Create Maximum Number",
    difficulty: "Hard",
    topic: ["Array", "Two Pointers", "Stack", "Greedy", "Monotonic Stack"],
    link: "https://leetcode.com/problems/create-maximum-number/",
  },
  {
    title: "Count of Range Sum",
    difficulty: "Hard",
    topic: [
      "Array",
      "Binary Search",
      "Divide and Conquer",
      "Binary Indexed Tree",
      "Segment Tree",
      "Merge Sort",
      "Ordered Set",
    ],
    link: "https://leetcode.com/problems/count-of-range-sum/",
  },
  {
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    topic: [
      "Array",
      "Dynamic Programming",
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
      "Memoization",
      "Matrix",
    ],
    link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
  },
  {
    title: "Patching Array",
    difficulty: "Hard",
    topic: ["Array", "Greedy"],
    link: "https://leetcode.com/problems/patching-array/",
  },
  {
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    topic: ["Depth-First Search", "Graph", "Eulerian Circuit"],
    link: "https://leetcode.com/problems/reconstruct-itinerary/",
  },
  {
    title: "Self Crossing",
    difficulty: "Hard",
    topic: ["Array", "Math", "Geometry"],
    link: "https://leetcode.com/problems/self-crossing/",
  },
  {
    title: "Palindrome Pairs",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "String", "Trie"],
    link: "https://leetcode.com/problems/palindrome-pairs/",
  },
  {
    title: "Data Stream as Disjoint Intervals",
    difficulty: "Hard",
    topic: ["Binary Search", "Design", "Ordered Set"],
    link: "https://leetcode.com/problems/data-stream-as-disjoint-intervals/",
  },
  {
    title: "Russian Doll Envelopes",
    difficulty: "Hard",
    topic: ["Array", "Binary Search", "Dynamic Programming", "Sorting"],
    link: "https://leetcode.com/problems/russian-doll-envelopes/",
  },
  {
    title: "Max Sum of Rectangle No Larger Than K",
    difficulty: "Hard",
    topic: ["Array", "Binary Search", "Matrix", "Prefix Sum", "Ordered Set"],
    link: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/",
  },
  {
    title: "Insert Delete GetRandom O(1) - Duplicates allowed",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "Math", "Design", "Randomized"],
    link: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/",
  },
  {
    title: "Perfect Rectangle",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "Math", "Geometry", "Line Sweep"],
    link: "https://leetcode.com/problems/perfect-rectangle/",
  },
  {
    title: "Frog Jump",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/frog-jump/",
  },
  {
    title: "Trapping Rain Water II",
    difficulty: "Hard",
    topic: ["Array", "Breadth-First Search", "Heap (Priority Queue)", "Matrix"],
    link: "https://leetcode.com/problems/trapping-rain-water-ii/",
  },
  {
    title: "Split Array Largest Sum",
    difficulty: "Hard",
    topic: [
      "Array",
      "Binary Search",
      "Dynamic Programming",
      "Greedy",
      "Prefix Sum",
    ],
    link: "https://leetcode.com/problems/split-array-largest-sum/",
  },
  {
    title: "Strong Password Checker",
    difficulty: "Hard",
    topic: ["String", "Greedy", "Heap (Priority Queue)"],
    link: "https://leetcode.com/problems/strong-password-checker/",
  },
  {
    title: "All O`one Data Structure",
    difficulty: "Hard",
    topic: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    link: "https://leetcode.com/problems/all-oone-data-structure/",
  },
  {
    title: "K-th Smallest in Lexicographical Order",
    difficulty: "Hard",
    topic: ["Trie"],
    link: "https://leetcode.com/problems/k-th-smallest-in-lexicographical-order/",
  },
  {
    title: "Arithmetic Slices II - Subsequence",
    difficulty: "Hard",
    topic: ["Array", "Dynamic Programming"],
    link: "https://leetcode.com/problems/arithmetic-slices-ii-subsequence/",
  },
  {
    title: "Poor Pigs",
    difficulty: "Hard",
    topic: ["Math", "Dynamic Programming", "Combinatorics"],
    link: "https://leetcode.com/problems/poor-pigs/",
  },
  {
    title: "LFU Cache",
    difficulty: "Hard",
    topic: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    link: "https://leetcode.com/problems/lfu-cache/",
  },
  {
    title: "Count The Repetitions",
    difficulty: "Hard",
    topic: ["String", "Dynamic Programming"],
    link: "https://leetcode.com/problems/count-the-repetitions/",
  },
  {
    title: "Concatenated Words",
    difficulty: "Hard",
    topic: [
      "Array",
      "String",
      "Dynamic Programming",
      "Depth-First Search",
      "Trie",
      "Sorting",
    ],
    link: "https://leetcode.com/problems/concatenated-words/",
  },
  {
    title: "Largest Palindrome Product",
    difficulty: "Hard",
    topic: ["Math", "Enumeration"],
    link: "https://leetcode.com/problems/largest-palindrome-product/",
  },
  {
    title: "Sliding Window Median",
    difficulty: "Hard",
    topic: ["Array", "Hash Table", "Sliding Window", "Heap (Priority Queue)"],
    link: "https://leetcode.com/problems/sliding-window-median/",
  },
  {
    title: "Smallest Good Base",
    difficulty: "Hard",
    topic: ["Math", "Binary Search"],
    link: "https://leetcode.com/problems/smallest-good-base/",
  },
  {
    title: "Zuma Game",
    difficulty: "Hard",
    topic: [
      "String",
      "Dynamic Programming",
      "Stack",
      "Breadth-First Search",
      "Memoization",
    ],
    link: "https://leetcode.com/problems/zuma-game/",
  },
  {
    title: "Reverse Pairs",
    difficulty: "Hard",
    topic: [
      "Array",
      "Binary Search",
      "Divide and Conquer",
      "Binary Indexed Tree",
      "Segment Tree",
      "Merge Sort",
      "Ordered Set",
    ],
    link: "https://leetcode.com/problems/reverse-pairs/",
  },
];

const seed = async () => {
  await connectDB();

  await Recommendation.deleteMany();

  await Recommendation.insertMany(problems);

  console.log("Seeded");

  process.exit();
};

seed();
